// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: mangahub.proto

package mangahubpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Manga struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Genres        []string               `protobuf:"bytes,4,rep,name=genres,proto3" json:"genres,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	TotalChapters int32                  `protobuf:"varint,6,opt,name=total_chapters,json=totalChapters,proto3" json:"total_chapters,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,8,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manga) Reset() {
	*x = Manga{}
	mi := &file_mangahub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manga) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manga) ProtoMessage() {}

func (x *Manga) ProtoReflect() protoreflect.Message {
	mi := &file_mangahub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manga.ProtoReflect.Descriptor instead.
func (*Manga) Descriptor() ([]byte, []int) {
	return file_mangahub_proto_rawDescGZIP(), []int{0}
}

func (x *Manga) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Manga) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Manga) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Manga) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *Manga) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Manga) GetTotalChapters() int32 {
	if x != nil {
		return x.TotalChapters
	}
	return 0
}

func (x *Manga) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Manga) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

type GetMangaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMangaRequest) Reset() {
	*x = GetMangaRequest{}
	mi := &file_mangahub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMangaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMangaRequest) ProtoMessage() {}

func (x *GetMangaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mangahub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMangaRequest.ProtoReflect.Descriptor instead.
func (*GetMangaRequest) Descriptor() ([]byte, []int) {
	return file_mangahub_proto_rawDescGZIP(), []int{1}
}

func (x *GetMangaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Author        string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Genre         string                 `protobuf:"bytes,3,opt,name=genre,proto3" json:"genre,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_mangahub_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mangahub_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_mangahub_proto_rawDescGZIP(), []int{2}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *SearchRequest) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *SearchRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Manga               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_mangahub_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mangahub_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_mangahub_proto_rawDescGZIP(), []int{3}
}

func (x *SearchResponse) GetItems() []*Manga {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SearchResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ProgressRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MangaId        string                 `protobuf:"bytes,1,opt,name=manga_id,json=mangaId,proto3" json:"manga_id,omitempty"`
	ListName       string                 `protobuf:"bytes,2,opt,name=list_name,json=listName,proto3" json:"list_name,omitempty"`
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CurrentChapter int32                  `protobuf:"varint,4,opt,name=current_chapter,json=currentChapter,proto3" json:"current_chapter,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProgressRequest) Reset() {
	*x = ProgressRequest{}
	mi := &file_mangahub_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressRequest) ProtoMessage() {}

func (x *ProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mangahub_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressRequest.ProtoReflect.Descriptor instead.
func (*ProgressRequest) Descriptor() ([]byte, []int) {
	return file_mangahub_proto_rawDescGZIP(), []int{4}
}

func (x *ProgressRequest) GetMangaId() string {
	if x != nil {
		return x.MangaId
	}
	return ""
}

func (x *ProgressRequest) GetListName() string {
	if x != nil {
		return x.ListName
	}
	return ""
}

func (x *ProgressRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProgressRequest) GetCurrentChapter() int32 {
	if x != nil {
		return x.CurrentChapter
	}
	return 0
}

type ProgressResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Message        string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	MangaId        string                 `protobuf:"bytes,2,opt,name=manga_id,json=mangaId,proto3" json:"manga_id,omitempty"`
	ListName       string                 `protobuf:"bytes,3,opt,name=list_name,json=listName,proto3" json:"list_name,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CurrentChapter int32                  `protobuf:"varint,5,opt,name=current_chapter,json=currentChapter,proto3" json:"current_chapter,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProgressResponse) Reset() {
	*x = ProgressResponse{}
	mi := &file_mangahub_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressResponse) ProtoMessage() {}

func (x *ProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mangahub_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressResponse.ProtoReflect.Descriptor instead.
func (*ProgressResponse) Descriptor() ([]byte, []int) {
	return file_mangahub_proto_rawDescGZIP(), []int{5}
}

func (x *ProgressResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProgressResponse) GetMangaId() string {
	if x != nil {
		return x.MangaId
	}
	return ""
}

func (x *ProgressResponse) GetListName() string {
	if x != nil {
		return x.ListName
	}
	return ""
}

func (x *ProgressResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProgressResponse) GetCurrentChapter() int32 {
	if x != nil {
		return x.CurrentChapter
	}
	return 0
}

type ProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileResponse) Reset() {
	*x = ProfileResponse{}
	mi := &file_mangahub_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileResponse) ProtoMessage() {}

func (x *ProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mangahub_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileResponse.ProtoReflect.Descriptor instead.
func (*ProfileResponse) Descriptor() ([]byte, []int) {
	return file_mangahub_proto_rawDescGZIP(), []int{6}
}

func (x *ProfileResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProfileResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetLibraryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListName      string                 `protobuf:"bytes,1,opt,name=list_name,json=listName,proto3" json:"list_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLibraryRequest) Reset() {
	*x = GetLibraryRequest{}
	mi := &file_mangahub_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLibraryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLibraryRequest) ProtoMessage() {}

func (x *GetLibraryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mangahub_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLibraryRequest.ProtoReflect.Descriptor instead.
func (*GetLibraryRequest) Descriptor() ([]byte, []int) {
	return file_mangahub_proto_rawDescGZIP(), []int{7}
}

func (x *GetLibraryRequest) GetListName() string {
	if x != nil {
		return x.ListName
	}
	return ""
}

type LibraryItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ListName       string                 `protobuf:"bytes,1,opt,name=list_name,json=listName,proto3" json:"list_name,omitempty"`
	Manga          *Manga                 `protobuf:"bytes,2,opt,name=manga,proto3" json:"manga,omitempty"`
	CurrentChapter int32                  `protobuf:"varint,3,opt,name=current_chapter,json=currentChapter,proto3" json:"current_chapter,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LibraryItem) Reset() {
	*x = LibraryItem{}
	mi := &file_mangahub_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LibraryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LibraryItem) ProtoMessage() {}

func (x *LibraryItem) ProtoReflect() protoreflect.Message {
	mi := &file_mangahub_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LibraryItem.ProtoReflect.Descriptor instead.
func (*LibraryItem) Descriptor() ([]byte, []int) {
	return file_mangahub_proto_rawDescGZIP(), []int{8}
}

func (x *LibraryItem) GetListName() string {
	if x != nil {
		return x.ListName
	}
	return ""
}

func (x *LibraryItem) GetManga() *Manga {
	if x != nil {
		return x.Manga
	}
	return nil
}

func (x *LibraryItem) GetCurrentChapter() int32 {
	if x != nil {
		return x.CurrentChapter
	}
	return 0
}

func (x *LibraryItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LibraryItem) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type LibraryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*LibraryItem         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LibraryResponse) Reset() {
	*x = LibraryResponse{}
	mi := &file_mangahub_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LibraryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LibraryResponse) ProtoMessage() {}

func (x *LibraryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mangahub_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LibraryResponse.ProtoReflect.Descriptor instead.
func (*LibraryResponse) Descriptor() ([]byte, []int) {
	return file_mangahub_proto_rawDescGZIP(), []int{9}
}

func (x *LibraryResponse) GetItems() []*LibraryItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *LibraryResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_mangahub_proto protoreflect.FileDescriptor

const file_mangahub_proto_rawDesc = "" +
	"\n" +
	"\x0emangahub.proto\x12\vmangahub.v1\x1a\x1bgoogle/protobuf/empty.proto\"\xdb\x01\n" +
	"\x05Manga\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x16\n" +
	"\x06genres\x18\x04 \x03(\tR\x06genres\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12%\n" +
	"\x0etotal_chapters\x18\x06 \x01(\x05R\rtotalChapters\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x1b\n" +
	"\tcover_url\x18\b \x01(\tR\bcoverUrl\"!\n" +
	"\x0fGetMangaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x99\x01\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x14\n" +
	"\x05genre\x18\x03 \x01(\tR\x05genre\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x05R\x06offset\"P\n" +
	"\x0eSearchResponse\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.mangahub.v1.MangaR\x05items\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\x8a\x01\n" +
	"\x0fProgressRequest\x12\x19\n" +
	"\bmanga_id\x18\x01 \x01(\tR\amangaId\x12\x1b\n" +
	"\tlist_name\x18\x02 \x01(\tR\blistName\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12'\n" +
	"\x0fcurrent_chapter\x18\x04 \x01(\x05R\x0ecurrentChapter\"\xa5\x01\n" +
	"\x10ProgressResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x19\n" +
	"\bmanga_id\x18\x02 \x01(\tR\amangaId\x12\x1b\n" +
	"\tlist_name\x18\x03 \x01(\tR\blistName\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12'\n" +
	"\x0fcurrent_chapter\x18\x05 \x01(\x05R\x0ecurrentChapter\"=\n" +
	"\x0fProfileResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"0\n" +
	"\x11GetLibraryRequest\x12\x1b\n" +
	"\tlist_name\x18\x01 \x01(\tR\blistName\"\xb4\x01\n" +
	"\vLibraryItem\x12\x1b\n" +
	"\tlist_name\x18\x01 \x01(\tR\blistName\x12(\n" +
	"\x05manga\x18\x02 \x01(\v2\x12.mangahub.v1.MangaR\x05manga\x12'\n" +
	"\x0fcurrent_chapter\x18\x03 \x01(\x05R\x0ecurrentChapter\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\"W\n" +
	"\x0fLibraryResponse\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x18.mangahub.v1.LibraryItemR\x05items\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count2\xe3\x01\n" +
	"\fMangaService\x12<\n" +
	"\bGetManga\x12\x1c.mangahub.v1.GetMangaRequest\x1a\x12.mangahub.v1.Manga\x12F\n" +
	"\vSearchManga\x12\x1a.mangahub.v1.SearchRequest\x1a\x1b.mangahub.v1.SearchResponse\x12M\n" +
	"\x0eUpdateProgress\x12\x1c.mangahub.v1.ProgressRequest\x1a\x1d.mangahub.v1.ProgressResponse2\x9d\x01\n" +
	"\vUserService\x12B\n" +
	"\n" +
	"GetProfile\x12\x16.google.protobuf.Empty\x1a\x1c.mangahub.v1.ProfileResponse\x12J\n" +
	"\n" +
	"GetLibrary\x12\x1e.mangahub.v1.GetLibraryRequest\x1a\x1c.mangahub.v1.LibraryResponseB\x1bZ\x19MangaHub/proto/mangahubpbb\x06proto3"

var (
	file_mangahub_proto_rawDescOnce sync.Once
	file_mangahub_proto_rawDescData []byte
)

func file_mangahub_proto_rawDescGZIP() []byte {
	file_mangahub_proto_rawDescOnce.Do(func() {
		file_mangahub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mangahub_proto_rawDesc), len(file_mangahub_proto_rawDesc)))
	})
	return file_mangahub_proto_rawDescData
}

var file_mangahub_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_mangahub_proto_goTypes = []any{
	(*Manga)(nil),             // 0: mangahub.v1.Manga
	(*GetMangaRequest)(nil),   // 1: mangahub.v1.GetMangaRequest
	(*SearchRequest)(nil),     // 2: mangahub.v1.SearchRequest
	(*SearchResponse)(nil),    // 3: mangahub.v1.SearchResponse
	(*ProgressRequest)(nil),   // 4: mangahub.v1.ProgressRequest
	(*ProgressResponse)(nil),  // 5: mangahub.v1.ProgressResponse
	(*ProfileResponse)(nil),   // 6: mangahub.v1.ProfileResponse
	(*GetLibraryRequest)(nil), // 7: mangahub.v1.GetLibraryRequest
	(*LibraryItem)(nil),       // 8: mangahub.v1.LibraryItem
	(*LibraryResponse)(nil),   // 9: mangahub.v1.LibraryResponse
	(*emptypb.Empty)(nil),     // 10: google.protobuf.Empty
}
var file_mangahub_proto_depIdxs = []int32{
	0,  // 0: mangahub.v1.SearchResponse.items:type_name -> mangahub.v1.Manga
	0,  // 1: mangahub.v1.LibraryItem.manga:type_name -> mangahub.v1.Manga
	8,  // 2: mangahub.v1.LibraryResponse.items:type_name -> mangahub.v1.LibraryItem
	1,  // 3: mangahub.v1.MangaService.GetManga:input_type -> mangahub.v1.GetMangaRequest
	2,  // 4: mangahub.v1.MangaService.SearchManga:input_type -> mangahub.v1.SearchRequest
	4,  // 5: mangahub.v1.MangaService.UpdateProgress:input_type -> mangahub.v1.ProgressRequest
	10, // 6: mangahub.v1.UserService.GetProfile:input_type -> google.protobuf.Empty
	7,  // 7: mangahub.v1.UserService.GetLibrary:input_type -> mangahub.v1.GetLibraryRequest
	0,  // 8: mangahub.v1.MangaService.GetManga:output_type -> mangahub.v1.Manga
	3,  // 9: mangahub.v1.MangaService.SearchManga:output_type -> mangahub.v1.SearchResponse
	5,  // 10: mangahub.v1.MangaService.UpdateProgress:output_type -> mangahub.v1.ProgressResponse
	6,  // 11: mangahub.v1.UserService.GetProfile:output_type -> mangahub.v1.ProfileResponse
	9,  // 12: mangahub.v1.UserService.GetLibrary:output_type -> mangahub.v1.LibraryResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_mangahub_proto_init() }
func file_mangahub_proto_init() {
	if File_mangahub_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mangahub_proto_rawDesc), len(file_mangahub_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_mangahub_proto_goTypes,
		DependencyIndexes: file_mangahub_proto_depIdxs,
		MessageInfos:      file_mangahub_proto_msgTypes,
	}.Build()
	File_mangahub_proto = out.File
	file_mangahub_proto_goTypes = nil
	file_mangahub_proto_depIdxs = nil
}
