name: MangaHub CI

# CI sẽ tự động chạy khi bạn push code lên nhánh main hoặc tạo Pull Request
on:
  push:
    branches: ["main", "master", "dev"]
  pull_request:
    branches: ["main", "master"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source code from repository
      - name: Checkout Source Code
        uses: actions/checkout@v4

      # 2. install Go 1.25
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.6"

      # 3. install project dependencies
      - name: Install Dependencies
        run: go mod tidy

      # 4. Build API Server to check for compilation errors
      - name: Build API Server
        env:
          CGO_ENABLED: 1
        run: go build -v ./cmd/api-server/...

      # 5. Verify Docker Compose Build
      - name: Verify Docker Compose Build
        run: docker-compose build
